name: Auto Scan and Update Cydia Repo

on:
  push:
    paths:
      - 'Packages'
      - 'debs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dpkg-dev tools
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev

    - name: Scan Packages automatically
      run: |
        dpkg-scanpackages -m debs /dev/null > Packages
        sed -i 's/\r$//' Packages
        bzip2 -fk Packages

    - name: Commit and Push to GitHub
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        git add Packages Packages.bz2
        git commit -m "Auto updated Repo: Changes detected!" || exit 0
        git push
